# -*- coding: utf-8 -*-
"""Constants used by recommendation scoring and ranking."""

from src.recommendation.models import ScoringWeights

BUY_NOW_MIN_SCORE = 80.0
POSITION_MIN_SCORE = 60.0
WAIT_PULLBACK_MIN_SCORE = 40.0

CN_STOP_LOSS_RATIO = 0.93
CN_TAKE_PROFIT_RATIO = 1.10
RISK_MAX_HOLD_DAYS = 10

DEFAULT_TOP_N_PER_SECTOR = 10
DEFAULT_SCORING_WEIGHTS = ScoringWeights()

TECHNICAL_BASE_WEIGHT = 0.8
TECHNICAL_DELEGATED_WEIGHT = 0.2

TECHNICAL_SHRINK_VOLUME_MAX = 0.7
TECHNICAL_PULLBACK_NEAR_MA10_MAX_ABS = 0.02
TECHNICAL_SHRINK_VOLUME_BONUS = 5.0
TECHNICAL_SHRINK_VOLUME_PULLBACK_BONUS = 8.0

TECHNICAL_HEAVY_VOLUME_PENALTY_MIN = 2.0
TECHNICAL_HEAVY_VOLUME_PENALTY_HIGH = 3.0
TECHNICAL_HEAVY_VOLUME_PENALTY_LOW_SCORE = -5.0
TECHNICAL_HEAVY_VOLUME_PENALTY_HIGH_SCORE = -10.0

TECHNICAL_MODERATE_VOLUME_MIN = 1.0
TECHNICAL_MODERATE_VOLUME_MAX = 2.0
TECHNICAL_MODERATE_VOLUME_DELTA = 0.0

TECHNICAL_COUNTER_TREND_MA20_MAX = 0.0
TECHNICAL_COUNTER_TREND_MA20_BONUS = 5.0
TECHNICAL_COUNTER_TREND_MA60_MAX = 0.0
TECHNICAL_COUNTER_TREND_MA60_BONUS = 3.0
